---
hostname:
  description: "Digital Loggers Web Switch FQDN"
  type: "string"
  required: true
username:
  description: "Username for web switch"
  type: "string"
  secret: true
  required: true
password:
  description: "Password for web switch"
  type: "string"
  secret: true
  required: true
